import type { AgentToolSchema, GraphWorkspaceCapabilityModel, GraphWorkspaceMcpContract } from "./types.ts";

const OK_DATA_OUTPUT_SCHEMA = {
  type: "object",
  required: ["ok", "data"],
} satisfies Record<string, unknown>;

const OK_OUTPUT_SCHEMA = {
  type: "object",
  required: ["ok"],
} satisfies Record<string, unknown>;

function defineTool(args: AgentToolSchema): AgentToolSchema {
  return args;
}

export const GRAPH_WORKSPACE_CAPABILITY_MODEL: GraphWorkspaceCapabilityModel = {
  resource: {
    name: "graph_workspace",
    description: "当前正在编辑的知识图谱工作区，稳定标识为活动工作区。",
    stableId: "graph_workspace:active",
  },
  queries: [
    "describe_active_workspace",
    "describe_persistence_target",
    "get_execution_state",
    "list_pending_approvals",
    "get_workspace_snapshot",
    "list_nodes",
    "get_node",
    "list_edges",
    "compute_shortest_path",
  ],
  actions: [
    "save_workspace",
    "import_graph_data",
    "request_json_export",
    "take_over_session",
    "create_node",
    "update_node",
    "delete_nodes",
    "duplicate_nodes",
    "create_edge",
    "update_edge_label",
    "delete_edges",
  ],
  approvals: [
    "approve_pending_action",
    "reject_pending_action",
  ],
  tasks: [
    "workspace_save_task",
    "json_export_task",
  ],
  events: [
    "graph.workspace.changed",
    "graph.workspace.save.started",
    "graph.workspace.save.succeeded",
    "graph.workspace.save.failed",
    "graph.workspace.import.started",
    "graph.workspace.import.succeeded",
    "graph.workspace.import.failed",
    "graph.workspace.export.requires_approval",
    "graph.workspace.export.running",
    "graph.workspace.export.succeeded",
    "graph.workspace.export.failed",
    "agent.session.taken_over",
  ],
};

export const GRAPH_WORKSPACE_TOOLS: AgentToolSchema[] = [
  defineTool({
    name: "describe_active_workspace",
    kind: "query",
    goal: "读取当前活动工作区的结构化摘要。",
    description: "返回节点数、连线数、选中节点数、保存状态与工作区 revision。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: [],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "describe_persistence_target",
    kind: "query",
    goal: "读取当前持久化后端与落盘位置。",
    description: "返回当前落盘位置、存在状态、字节大小和更新时间。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: ["EXTERNAL_FAILURE"],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "get_execution_state",
    kind: "query",
    goal: "读取当前结构化执行状态。",
    description: "返回 session、task、approval 与事件流快照。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: [],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "list_pending_approvals",
    kind: "query",
    goal: "列出当前仍待处理的审批项。",
    description: "适合 supervisor 或 operator 轮询待审批高风险动作。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: [],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "get_workspace_snapshot",
    kind: "query",
    goal: "读取当前工作区完整快照。",
    description: "返回图数据、选中信息、saveStatus、revision 与 summary。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: [],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "list_nodes",
    kind: "query",
    goal: "列出当前工作区的全部节点。",
    description: "返回节点列表，可用于 agent 构建局部决策上下文。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: [],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "get_node",
    kind: "query",
    goal: "读取单个节点详情。",
    description: "按节点 ID 返回节点数据。",
    inputSchema: {
      type: "object",
      properties: {
        nodeId: { type: "string" },
      },
      required: ["nodeId"],
      additionalProperties: false,
    },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: ["nodeId 必须存在于当前工作区"],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "list_edges",
    kind: "query",
    goal: "列出当前工作区的全部连线。",
    description: "返回边列表，可用于结构推理或差异比对。",
    inputSchema: { type: "object", properties: {}, additionalProperties: false },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: [],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "compute_shortest_path",
    kind: "query",
    goal: "计算两个节点之间的最短路径。",
    description: "支持 directed / undirected 两种模式，返回节点路径与边路径。",
    inputSchema: {
      type: "object",
      properties: {
        startNodeId: { type: "string" },
        endNodeId: { type: "string" },
        mode: { type: "string", enum: ["directed", "undirected"] },
      },
      required: ["startNodeId", "endNodeId"],
      additionalProperties: false,
    },
    outputSchema: OK_DATA_OUTPUT_SCHEMA,
    preconditions: ["startNodeId 和 endNodeId 都必须存在于当前工作区"],
    sideEffects: [],
    idempotency: "idempotent",
    confirmationRequirement: "none",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: [],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "save_workspace",
    kind: "action",
    goal: "把当前活动工作区保存到持久化后端。",
    description: "低风险落盘动作，供 UI 与 agent 共用。",
    inputSchema: {
      type: "object",
      properties: {
        actor: { type: "string", enum: ["human", "agent", "system"] },
        reason: { type: "string" },
      },
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: ["写入本地持久化后端"],
    idempotency: "conditionally_idempotent",
    confirmationRequirement: "none",
    failureModes: ["EXTERNAL_FAILURE"],
    observableEvents: [
      "graph.workspace.save.started",
      "graph.workspace.save.succeeded",
      "graph.workspace.save.failed",
    ],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "import_graph_data",
    kind: "action",
    goal: "用新的图数据替换当前工作区内容。",
    description: "适合文件导入、文本生成后应用到活动工作区。",
    inputSchema: {
      type: "object",
      properties: {
        actor: { type: "string", enum: ["human", "agent", "system"] },
        envelope: { type: "object" },
        replaceExisting: { type: "boolean" },
      },
      required: ["envelope"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["replaceExisting=false 时，当前工作区必须为空"],
    sideEffects: ["替换当前工作区图数据"],
    idempotency: "not_idempotent",
    confirmationRequirement: "none",
    failureModes: ["PRECONDITION_FAILED", "EXTERNAL_FAILURE"],
    observableEvents: [
      "graph.workspace.import.started",
      "graph.workspace.import.succeeded",
      "graph.workspace.import.failed",
      "graph.workspace.changed",
    ],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "request_json_export",
    kind: "action",
    goal: "为 JSON 导出创建任务和审批请求。",
    description: "高风险外部写入动作，先进入审批，再由批准动作真正写出文件。",
    inputSchema: {
      type: "object",
      properties: {
        actor: { type: "string", enum: ["human", "agent"] },
        scope: { type: "string", enum: ["all", "selected"] },
        filename: { type: "string" },
        reason: { type: "string" },
      },
      required: ["actor"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["scope=selected 时必须存在选中节点"],
    sideEffects: ["创建导出任务", "创建审批记录", "审批通过后写出 JSON 文件"],
    idempotency: "not_idempotent",
    confirmationRequirement: "human_approval_required",
    failureModes: ["PRECONDITION_FAILED", "APPROVAL_REQUIRED", "CONCURRENCY_CONFLICT", "EXTERNAL_FAILURE"],
    observableEvents: [
      "graph.workspace.export.requires_approval",
      "graph.workspace.export.running",
      "graph.workspace.export.succeeded",
      "graph.workspace.export.failed",
    ],
    visibility: "guarded",
  }),
  defineTool({
    name: "take_over_session",
    kind: "action",
    goal: "由人工接管当前 session。",
    description: "将当前 session 标记为 taken_over，阻止继续自动推进。",
    inputSchema: {
      type: "object",
      properties: {
        sessionId: { type: "string" },
        actor: { type: "string", enum: ["human", "supervisor"] },
        reason: { type: "string" },
      },
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["当前必须存在可接管的 session"],
    sideEffects: ["更新 session 状态"],
    idempotency: "not_idempotent",
    confirmationRequirement: "human_confirmation_required",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: ["agent.session.taken_over"],
    visibility: "guarded",
  }),
  defineTool({
    name: "create_node",
    kind: "action",
    goal: "在当前工作区新建节点。",
    description: "创建节点并返回新节点 ID。",
    inputSchema: {
      type: "object",
      properties: {
        label: { type: "string" },
        position: { type: "object" },
        content: { type: "string" },
      },
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: [],
    sideEffects: ["修改当前工作区图数据"],
    idempotency: "not_idempotent",
    confirmationRequirement: "none",
    failureModes: ["EXTERNAL_FAILURE"],
    observableEvents: ["graph.workspace.changed"],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "update_node",
    kind: "action",
    goal: "更新指定节点的数据或位置。",
    description: "支持更新 label、content、tags、颜色、锁定信息和位置。",
    inputSchema: {
      type: "object",
      properties: {
        nodeId: { type: "string" },
        patch: { type: "object" },
      },
      required: ["nodeId", "patch"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["nodeId 必须存在于当前工作区"],
    sideEffects: ["修改当前工作区图数据"],
    idempotency: "not_idempotent",
    confirmationRequirement: "none",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: ["graph.workspace.changed"],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "delete_nodes",
    kind: "action",
    goal: "删除一个或多个节点。",
    description: "删除节点时会一并删除关联连线。",
    inputSchema: {
      type: "object",
      properties: {
        nodeIds: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["nodeIds"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["nodeIds 至少包含一个有效节点 ID"],
    sideEffects: ["删除节点和关联边"],
    idempotency: "not_idempotent",
    confirmationRequirement: "human_confirmation_required",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: ["graph.workspace.changed"],
    visibility: "guarded",
  }),
  defineTool({
    name: "duplicate_nodes",
    kind: "action",
    goal: "复制一个或多个节点。",
    description: "保留节点数据，并复制选中节点之间的内部连线。",
    inputSchema: {
      type: "object",
      properties: {
        nodeIds: {
          type: "array",
          items: { type: "string" },
        },
      },
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["nodeIds 为空时，将退回使用当前选中节点"],
    sideEffects: ["新增节点和边"],
    idempotency: "not_idempotent",
    confirmationRequirement: "none",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: ["graph.workspace.changed"],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "create_edge",
    kind: "action",
    goal: "在两个节点之间创建连线。",
    description: "默认创建中心连线，可附带 label。",
    inputSchema: {
      type: "object",
      properties: {
        source: { type: "string" },
        target: { type: "string" },
        label: { type: "string" },
      },
      required: ["source", "target"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["source 和 target 必须都存在"],
    sideEffects: ["新增连线"],
    idempotency: "not_idempotent",
    confirmationRequirement: "none",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: ["graph.workspace.changed"],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "update_edge_label",
    kind: "action",
    goal: "更新指定连线的标签。",
    description: "用于维护节点关系语义。",
    inputSchema: {
      type: "object",
      properties: {
        edgeId: { type: "string" },
        label: { type: "string" },
      },
      required: ["edgeId", "label"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["edgeId 必须存在于当前工作区"],
    sideEffects: ["修改边标签"],
    idempotency: "not_idempotent",
    confirmationRequirement: "none",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: ["graph.workspace.changed"],
    visibility: "safe_by_default",
  }),
  defineTool({
    name: "delete_edges",
    kind: "action",
    goal: "删除一个或多个连线。",
    description: "按边 ID 批量删除连线。",
    inputSchema: {
      type: "object",
      properties: {
        edgeIds: {
          type: "array",
          items: { type: "string" },
        },
      },
      required: ["edgeIds"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["edgeIds 至少包含一个有效边 ID"],
    sideEffects: ["删除连线"],
    idempotency: "not_idempotent",
    confirmationRequirement: "human_confirmation_required",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: ["graph.workspace.changed"],
    visibility: "guarded",
  }),
  defineTool({
    name: "approve_pending_action",
    kind: "approval",
    goal: "批准待处理的高风险动作。",
    description: "当前用于批准受管 JSON 导出；桌面端应传入明确的 outputPath。",
    inputSchema: {
      type: "object",
      properties: {
        approvalId: { type: "string" },
        actor: { type: "string", enum: ["human", "supervisor"] },
        outputPath: { type: "string" },
      },
      required: ["approvalId"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["approvalId 对应的审批必须存在且仍处于 requested 状态"],
    sideEffects: ["推进审批、任务和 session 状态机，必要时写出文件"],
    idempotency: "not_idempotent",
    confirmationRequirement: "human_confirmation_required",
    failureModes: ["PRECONDITION_FAILED", "CONCURRENCY_CONFLICT", "EXTERNAL_FAILURE"],
    observableEvents: [
      "graph.workspace.export.running",
      "graph.workspace.export.succeeded",
      "graph.workspace.export.failed",
    ],
    visibility: "guarded",
  }),
  defineTool({
    name: "reject_pending_action",
    kind: "approval",
    goal: "拒绝待处理的高风险动作。",
    description: "当前用于拒绝受管 JSON 导出。",
    inputSchema: {
      type: "object",
      properties: {
        approvalId: { type: "string" },
        actor: { type: "string", enum: ["human", "supervisor"] },
        reason: { type: "string" },
      },
      required: ["approvalId"],
      additionalProperties: false,
    },
    outputSchema: OK_OUTPUT_SCHEMA,
    preconditions: ["approvalId 对应的审批必须存在且仍处于 requested 状态"],
    sideEffects: ["终止任务并记录拒绝原因"],
    idempotency: "not_idempotent",
    confirmationRequirement: "human_confirmation_required",
    failureModes: ["PRECONDITION_FAILED"],
    observableEvents: ["graph.workspace.export.failed"],
    visibility: "guarded",
  }),
];

export const GRAPH_WORKSPACE_MCP_CONTRACT: GraphWorkspaceMcpContract = {
  version: "0.2.0",
  resource: GRAPH_WORKSPACE_CAPABILITY_MODEL.resource,
  tools: GRAPH_WORKSPACE_TOOLS,
};
